# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Khipu Inside Demo' do
    # Uncomment this line if you're using Swift or would like to use dynamic frameworks
    use_frameworks!

    # Pods for Khipu Inside Demo
    pod 'khenshin' #Fija la versión antes de pasar a producción
end
